In [1]:
import os
import dotenv
import pandas as pd
from kaggle.api.kaggle_api_extended import KaggleApi

dotenv.load_dotenv()

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2)

True

In [2]:
os.environ['KAGGLE_USERNAME'] = os.getenv("KAGGLE_USERNAME")
os.environ['KAGGLE_KEY'] = os.getenv("KAGGLE_KEY")

api = KaggleApi()
api.authenticate()

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2)

In [3]:
def download_dataset(dataset, path):
    api.dataset_download_files(dataset, path=path, unzip=True)

In [4]:
dataset = os.getenv("DATASET")
path = f'../data/kaggle/raw/{dataset.split("/")[1]}/'

download_dataset(dataset, path)

Dataset URL: https://www.kaggle.com/datasets/tunguz/bank-marketing-data-set

In [5]:
csvs = os.listdir(path)
csvs

['bank-additional-full.csv',
 'bank-full.csv',
 'bank-additional.csv',
 'bank.csv']

In [6]:
df = pd.read_csv(f'{path}/{csvs[3]}', sep=';')
df = df.dropna()

In [7]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [8]:
clean_df = df[[
    'age',
    'job',
    'marital',
    'education',
    'balance',
    'housing',
    'loan',
    'pdays',
    'previous',
    'poutcome'
]]
clean_df

,age,job,marital,education,balance,housing,loan,pdays,previous,poutcome
0,30,unemployed,married,primary,1787,no,no,-1,0,unknown
1,33,services,married,secondary,4789,yes,yes,339,4,failure
2,35,management,single,tertiary,1350,yes,no,330,1,failure
3,30,management,married,tertiary,1476,yes,yes,-1,0,unknown
4,59,blue-collar,married,secondary,0,yes,no,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,-333,yes,no,-1,0,unknown
4517,57,self-employed,married,tertiary,-3313,yes,yes,-1,0,unknown
4518,57,technician,married,secondary,295,no,no,-1,0,unknown
4519,28,blue-collar,married,secondary,1137,no,no,211,3,other
4520,44,entrepreneur,single,tertiary,1136,yes,yes,249,7,other

In [10]:
clean_dataset_path = str(os.getenv("CLEAN_DATASET_PATH"))

os.makedirs(clean_dataset_path, exist_ok=True)
clean_df.to_parquet(f'{clean_dataset_path}/clean_bank.parquet', index=False)

In [11]:
df.columns.difference(clean_df.columns)

Index(['campaign', 'contact', 'day', 'default', 'duration', 'month', 'y'], dtype='object')