In [28]:
import os
import pandas as pd
from kaggle.api.kaggle_api_extended import KaggleApi

import kaggle_variables as kaggle_variables

In [22]:
os.environ['KAGGLE_USERNAME'] = kaggle_variables.USERNAME
os.environ['KAGGLE_KEY'] = kaggle_variables.API_TOKEN

api = KaggleApi()
api.authenticate()

In [23]:
def download_dataset(dataset):
    api.dataset_download_files(dataset, path=f'raw/{dataset.split("/")[1]}/', unzip=True)

In [24]:
dataset = kaggle_variables.DATASET2
path = f'raw/{dataset.split("/")[1]}/'

download_dataset(dataset)

Dataset URL: https://www.kaggle.com/datasets/tunguz/bank-marketing-data-set

In [29]:
csvs = os.listdir(path)
csvs

['bank-additional-full.csv',
 'bank-additional.csv',
 'bank.csv',
 'bank-full.csv']

In [37]:
df = pd.read_csv(f'{path}/{csvs[3]}', sep=';')
df = df.dropna()

In [38]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [40]:
df = df[[
    'age',
    'job',
    'marital',
    'education',
    'balance',
    'housing',
    'loan',
    'pdays',
    'previous',
    'poutcome'
]]
df

,age,job,marital,education,balance,housing,loan,pdays,previous,poutcome
0,58,management,married,tertiary,2143,yes,no,-1,0,unknown
1,44,technician,single,secondary,29,yes,no,-1,0,unknown
2,33,entrepreneur,married,secondary,2,yes,yes,-1,0,unknown
3,47,blue-collar,married,unknown,1506,yes,no,-1,0,unknown
4,33,unknown,single,unknown,1,no,no,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,825,no,no,-1,0,unknown
45207,71,retired,divorced,primary,1729,no,no,-1,0,unknown
45208,72,retired,married,secondary,5715,no,no,184,3,success
45209,57,blue-collar,married,secondary,668,no,no,-1,0,unknown
45210,37,entrepreneur,married,secondary,2971,no,no,188,11,other